const routes = {
  homePage: '/',
  provideLiquidity: '/provideLiquidity',
  myEarnings: '/myEarnings',
  rewards: '/rewards',
  conversionHistory: '/conversionHistory',
  receiveAward: '/receiveAward',
  withdraw: '/withdraw',
  WithdrawHistory: '/withdrawHistory',
  withdrawal: '/withdrawal',
  exchange: '/exchange',
  currentRepayment: '/currentRepayment',
  // gettingStarted: '/',
  sign: '/sign',
  decrypt: '/decrypt',
  records: '/records',
  transfer: '/transfer',
  execute: '/execute',
  deploy: '/deploy',
  // loan: '/loan',
  // receiveLoan: '/receiveLoan',
  myLoan: '/myLoan',
  loanDetail: '/loanDetail',
  supplement: '/supplement',
};

export default routes;
